// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Serverside_Project_API.Model;

namespace Serverside_Project_API.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20211229091510_Project")]
    partial class Project
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Serverside_Project_API.Model.Commercial_Rent", b =>
                {
                    b.Property<int>("Commercial_Rent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age_Of_Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Building_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Deposit")
                        .HasColumnType("bigint");

                    b.Property<long>("Expected_Rent")
                        .HasColumnType("bigint");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Furnishing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ideal_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lease_Duration_Years")
                        .HasColumnType("int");

                    b.Property<string>("Lift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lockin_Period_Years")
                        .HasColumnType("int");

                    b.Property<string>("Other_Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Power_Backup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rent_Negotiable")
                        .HasColumnType("bit");

                    b.Property<bool>("Security")
                        .HasColumnType("bit");

                    b.Property<long>("Super_Built_Up_Area")
                        .HasColumnType("bigint");

                    b.Property<int>("Total_Floor")
                        .HasColumnType("int");

                    b.Property<string>("Washroom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Water_Storage_Facility")
                        .HasColumnType("bit");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("Commercial_Rent_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Commercial_Rents");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Commercial_Sale", b =>
                {
                    b.Property<int>("Commercial_Sale_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age_Of_Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Building_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Expected_Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Furnishing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ideal_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other_Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ownership_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Power_Backup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Price_Negotiable")
                        .HasColumnType("bit");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Security")
                        .HasColumnType("bit");

                    b.Property<long>("Super_Built_Up_Area")
                        .HasColumnType("bigint");

                    b.Property<int>("Total_Floor")
                        .HasColumnType("int");

                    b.Property<string>("Washroom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Water_Storage_Facility")
                        .HasColumnType("bit");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("Commercial_Sale_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Commercial_Sales");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Flatmates_Rent", b =>
                {
                    b.Property<int>("Flatmates_Rent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apartment_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Available_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("BHK_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Built_Up_Area")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Expected_Deposit")
                        .HasColumnType("bigint");

                    b.Property<long>("Expected_Rent")
                        .HasColumnType("bigint");

                    b.Property<string>("Facing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Furnishing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gated_Security")
                        .HasColumnType("bit");

                    b.Property<bool>("Gym")
                        .HasColumnType("bit");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Monthly_Maintenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Non_Veg_Allowed")
                        .HasColumnType("bit");

                    b.Property<int>("Number_Of_Balcony")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_Bathrooms")
                        .HasColumnType("int");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Property_Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rent_Negotiable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Secondary_Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Tenant_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Floor")
                        .HasColumnType("int");

                    b.Property<string>("Type_Of_Water_Supply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Who_Will_Show_The_House")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Flatmates_Rent_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Flatmates_Rents");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Pg_Hostel_Rent", b =>
                {
                    b.Property<int>("Pg_Hostel_Rent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Deposit_Per_Person")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Food_Included")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Gate_Clossing_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Laundry_Service_Available")
                        .HasColumnType("bit");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place_Available_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Preferred_Guests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Rent_Per_Person")
                        .HasColumnType("bigint");

                    b.Property<bool>("Room_Cleaning_Service_Available")
                        .HasColumnType("bit");

                    b.Property<string>("Type_Of_Rooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Warden_Facility_Service_Available")
                        .HasColumnType("bit");

                    b.HasKey("Pg_Hostel_Rent_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Pg_Hostel_Rents");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Post_Ad", b =>
                {
                    b.Property<int>("Post_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mobile_No")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Ad_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Post_Id");

                    b.ToTable("Post_Ads");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Resident_Rent", b =>
                {
                    b.Property<int>("Resident_Rent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apartment_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Available_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("BHK_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Built_Up_Area")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Expected_Deposit")
                        .HasColumnType("bigint");

                    b.Property<long>("Expected_Rent")
                        .HasColumnType("bigint");

                    b.Property<string>("Facing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Furnishing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gated_Security")
                        .HasColumnType("bit");

                    b.Property<bool>("Gym")
                        .HasColumnType("bit");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Monthly_Maintenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Non_Veg_Allowed")
                        .HasColumnType("bit");

                    b.Property<int>("Number_Of_Balcony")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_Bathrooms")
                        .HasColumnType("int");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Preferred_Tenants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rent_Negotiable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Secondary_Number")
                        .HasColumnType("bigint");

                    b.Property<int>("Total_Floor")
                        .HasColumnType("int");

                    b.Property<string>("Type_Of_Water_Supply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Who_Will_Show_The_House")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resident_Rent_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Resident_Rents");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Resident_Sale", b =>
                {
                    b.Property<int>("Resident_Sale_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apartment_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Available_From")
                        .HasColumnType("datetime2");

                    b.Property<string>("BHK_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Built_Up_Area")
                        .HasColumnType("bigint");

                    b.Property<long>("Carpet_Area")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Expected_Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Facing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Floor_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Furnishing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gated_Security")
                        .HasColumnType("bit");

                    b.Property<bool>("Gym")
                        .HasColumnType("bit");

                    b.Property<string>("Kitchen_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Maintenance_Cost")
                        .HasColumnType("bigint");

                    b.Property<int>("Number_Of_Balcony")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_Bathrooms")
                        .HasColumnType("int");

                    b.Property<string>("Ownership_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post_AdPost_Id")
                        .HasColumnType("int");

                    b.Property<string>("Power_Backup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Secondary_Number")
                        .HasColumnType("bigint");

                    b.Property<int>("Total_Floor")
                        .HasColumnType("int");

                    b.Property<string>("Type_Of_Water_Supply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Who_Will_Show_The_House")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resident_Sale_Id");

                    b.HasIndex("Post_AdPost_Id");

                    b.ToTable("Resident_Sales");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Commercial_Rent", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Commercial_Sale", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Flatmates_Rent", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Pg_Hostel_Rent", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Resident_Rent", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });

            modelBuilder.Entity("Serverside_Project_API.Model.Resident_Sale", b =>
                {
                    b.HasOne("Serverside_Project_API.Model.Post_Ad", "Post_Ad")
                        .WithMany()
                        .HasForeignKey("Post_AdPost_Id");

                    b.Navigation("Post_Ad");
                });
#pragma warning restore 612, 618
        }
    }
}
